name: Blog
'on':
  - workflow_dispatch
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install & Build
        run: >
          
          # Restore last modified time

          git ls-files -z | while read -d '' path; do touch -d "$(git log -1
          --format="@%ct" "$path")" "$path"; done

          hexo g
          
          pwd && ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: public
